export enum AccountType {
	ACCOUNT_MIHOYO_GUEST = 0,
	ACCOUNT_MIHOYO = 1,
	ACCOUNT_XIAOMI = 11,
	ACCOUNT_COOLPAD = 12,
	ACCOUNT_YYB = 13,
	ACCOUNT_BILI = 14,
	ACCOUNT_HUAWEI = 15,
	ACCOUNT_MEIZU = 16,
	ACCOUNT360 = 17,
	ACCOUNT_OPPO = 18,
	ACCOUNT_VIVO = 19,
	ACCOUNT_UC = 20,
	ACCOUNT_WANDOJIA = 21,
	ACCOUNT_LENOVO = 22,
	ACCOUNT_JINLI = 23,
	ACCOUNT_BAIDU = 25,
	ACCOUNT_DANGLE = 26
}

