export enum ChannelIdType {
	CHANNEL_ID_NONE = 0,
	CHANNEL_ID_MIHOYO = 1,
	CHANNEL_ID_XIAOMI = 11,
	CHANNEL_ID_COOLPAD = 12,
	CHANNEL_ID_YYB = 13,
	CHANNEL_ID_BILI = 14,
	CHANNEL_ID_HUAWEI = 15,
	CHANNEL_ID_MEIZU = 16,
	CHANNEL_ID360 = 17,
	CHANNEL_ID_OPPO = 18,
	CHANNEL_ID_VIVO = 19,
	CHANNEL_ID_UC = 20,
	CHANNEL_ID_LENOVO = 22,
	CHANNEL_ID_JINLI = 23,
	CHANNEL_ID_BAIDU = 25,
	CHANNEL_ID_DANGLE = 26
}

