export enum DungeonDataType {
	DUNGEON_DATA_NONE = 0,
	DUNGEON_DATA_END_TIME = 1,
	DUNGEON_DATA_MONSTER_DIE_COUNT = 2,
	DUNGEON_DATA_LEVEL_CONFIG_ID = 3,
	DUNGEON_DATA_TOWER_MONTHLY_LEVEL_CONFIG_ID = 4,
	DUNGEON_DATA_TOWER_FLOOR_LEVEL_CONFIG_ID = 5
}

