export enum FoundationOpType {
	FOUNDATION_OP_NONE = 0,
	FOUNDATION_OP_BUILD = 1,
	FOUNDATION_OP_DEMOLITION = 2,
	FOUNDATION_OP_REBUILD = 3,
	FOUNDATION_OP_ROTATE = 4,
	FOUNDATION_OP_LOCK = 5,
	FOUNDATION_OP_UNLOCK = 6
}

