export enum HideAndSeekStageType {
	HIDE_AND_SEEK_STAGE_PREPARE = 0,
	HIDE_AND_SEEK_STAGE_PICK = 1,
	HIDE_AND_SEEK_STAGE_GAME = 2,
	HIDE_AND_SEEK_STAGE_HIDE = 3,
	HIDE_AND_SEEK_STAGE_SEEK = 4,
	HIDE_AND_SEEK_STAGE_SETTLE = 5
}

