export enum InBattleMechanicusCardChallengeState {
	IN_BATTLE_MECHANICUS_CARD_CHALLENGE_NONE = 0,
	IN_BATTLE_MECHANICUS_CARD_CHALLENGE_ON_GOING = 1,
	IN_BATTLE_MECHANICUS_CARD_CHALLENGE_FAIL = 2,
	IN_BATTLE_MECHANICUS_CARD_CHALLENGE_SUCCESS = 3
}

