export enum InBattleMechanicusStageType {
	IN_BATTLE_MECHANICUS_STAGE_NONE = 0,
	IN_BATTLE_MECHANICUS_STAGE_BUILD = 1,
	IN_BATTLE_MECHANICUS_STAGE_CARD_FLIP = 2,
	IN_BATTLE_MECHANICUS_STAGE_KILL = 3
}

