export enum MatchReason {
	MATCH_NONE = 0,
	MATCH_FINISH = 1,
	MATCH_PLAYER_CANCEL = 2,
	MATCH_TIMEOUT = 3,
	MATCH_PLAYER_CONFIRM = 4,
	MATCH_FAILED = 5,
	MATCH_SYSTEM_ERROR = 6,
	MATCH_INTERRUPTED = 7,
	MATCH_MP_UNAVAILABLE = 8,
	MATCH_CONFIRM_TIMEOUT = 9
}

