export enum MonsterGuestBanDrop {
	MONSTER_GUEST_BAN_NONE = 0,
	MONSTER_GUEST_BAN_DIE_EXP = 1,
	MONSTER_GUEST_BAN_DIE_LUA = 2,
	MONSTER_GUEST_BAN_DIE_EXCEL = 4,
	MONSTER_GUEST_BAN_DIE_ACTIVITY = 8,
	HP = 16,
	MONSTER_GUEST_BAN_SUBFIELD = 32
}

