export enum ReportReasonType {
	REPORT_REASON_NONE = 0,
	REPORT_REASON_DECEPTIVE_ADS = 1,
	REPORT_REASON_ABUSING = 2,
	REPORT_REASON_CHEAT = 3,
	REPORT_REASON_POLITICAL = 4,
	REPORT_REASON_OTHER = 5,
	REPORT_REASON_HOME = 6
}

