export enum ScenePlayBattleState {
	SCENE_PLAY_BATTLE_NONE = 0,
	SCENE_PLAY_BATTLE_INIT = 1,
	SCENE_PLAY_BATTLE_PREPARE = 2,
	SCENE_PLAY_BATTLE_READY = 3,
	SCENE_PLAY_BATTLE_PRESTART = 4,
	SCENE_PLAY_BATTLE_START = 5,
	SCENE_PLAY_BATTLE_STOP = 6
}

