export enum SegmentCRCModuleType {
	MODULE_NONE = 0,
	PC_UNITYPLAYER = 1,
	PC_USERASSEMBLY = 2,
	PC_XLUA = 3,
	ANDROID_LIBIL2_CPP = 11,
	ANDROID_LIBUNITY = 12,
	ANDROID_LIBXLUA = 13,
	IOS_HK4_E = 21
}

